function StormEvents_2017_finalProject_1 = StormEvents(filename, dataLines)
%IMPORTFILE Import data from a text file
%  STORMEVENTS_2017_FINALPROJECT_1 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  STORMEVENTS_2017_FINALPROJECT_1 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  StormEvents_2017_finalProject_1 = importfile("/MATLAB Drive/Exploratory Data Analysis/StormEvents/StormEvents_2017_finalProject.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Aug-2025 19:23:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["EpisodeID", "Event_ID", "State", "Year", "Month", "Event_Type", "CZ_Name", "Begin_Date_Time", "Timezone", "End_Date_Time", "Injuries_Direct", "Injuries_Indirect", "Deaths_Direct", "Deaths_Indirect", "Damage_Property", "Property_Cost", "Damage_Crops", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon", "Episode_Narrative", "Event_Narrative"];
opts.SelectedVariableNames = ["Event_ID", "State", "Month", "Event_Type", "CZ_Name", "Begin_Date_Time", "End_Date_Time", "Injuries_Direct", "Deaths_Direct", "Property_Cost", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon"];
opts.VariableTypes = ["string", "double", "categorical", "string", "categorical", "categorical", "categorical", "datetime", "string", "datetime", "double", "string", "double", "string", "string", "double", "string", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["EpisodeID", "Year", "Timezone", "Injuries_Indirect", "Deaths_Indirect", "Damage_Property", "Damage_Crops", "Episode_Narrative", "Event_Narrative"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["EpisodeID", "State", "Year", "Month", "Event_Type", "CZ_Name", "Timezone", "Injuries_Indirect", "Deaths_Indirect", "Damage_Property", "Damage_Crops", "Episode_Narrative", "Event_Narrative"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Begin_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, "End_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
StormEvents_2017_finalProject_1 = readtable(filename, opts);

end